services:
  - type: web
    name: wsfeed-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py --host 0.0.0.0 --port $PORT
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: MODE
        value: quick
      - key: INSTRUMENT
        value: ES.c.0
      - key: WS_FORMAT
        value: text
    healthCheckPath: /
    plan: starter

